development:
  adapter: postgresql
  encoding: unicode
  database: vgifthost_development
  pool: 5
  username: newuser
  password: password
  host: localhost


test:
  adapter: postgresql
  encoding: unicode
  database: vgifthost_test
  pool: 5
  username: newuser
  password: password
  host: localhost

production:
  adapter: postgresql
  encoding: unicode
  database: vgifthost_production
  pool: 5
  username: newuser
  password: password
  host: localhost